"""Primitives B3 shares with the product, ported rather than reinvented.

Every constant here has a counterpart in `shared/` and the port is exact. A second definition of
"accurate", or a second win-probability curve, is the defect this repository has already been bitten
by: `shared/import-diagnostic.ts` records a call site that went on using a raw centipawn cut after
the detector's definition had moved to win-probability loss, so a third definition of the outcome
selected the hypothesis a different definition then graded. B3 does not add a fourth.

`tests/test_ports.py` checks each port against the TypeScript source it came from.
"""
from __future__ import annotations

import hashlib
import json
import math
import os
from typing import Iterable

# --- win probability -----------------------------------------------------------------------
# shared/win-probability.ts. Lichess's logistic from AccuracyPercent.scala, fitted on 2300-rated
# games, kept at their value so a number here can be checked against theirs. The caveat their file
# states applies here too and is repeated in the report: the constant is population-dependent, and
# B3 spans 800-2600, so the curve is not equally right across the range it is applied to.
WIN_PROBABILITY_K = 0.00368208

# client/src/lib/engine-line.ts: a mate is a ceiling, not a magnitude.
MATE_SCORE = 10000

# shared/detector.ts: 30 centipawns at a level position, in the unit that means the same thing twice.
ACCURATE_CP_LOSS = 30


def win_probability(cp: float) -> float:
    """Winning chances for the side to move, 0..1, from a centipawn score in their favour."""
    return 1.0 / (1.0 + math.exp(-WIN_PROBABILITY_K * cp))


def comparable_cp(score_kind: str, score_value: int) -> int:
    """A UCI score as a comparable centipawn number. `mate` saturates; it does not scale."""
    if score_kind == "mate":
        return MATE_SCORE if score_value > 0 else -MATE_SCORE
    return int(score_value)


def win_probability_loss(eval_cp: float, cp_loss: float) -> float:
    return max(0.0, win_probability(eval_cp) - win_probability(eval_cp - cp_loss))


# The B2-compatible binary threshold, DERIVED exactly as shared/detector.ts derives it:
# what 30cp costs at a level position (evaluated at cp_loss/2 so the interval is centred on level).
ACCURATE_WIN_PROBABILITY_LOSS = win_probability_loss(ACCURATE_CP_LOSS / 2, ACCURATE_CP_LOSS)

# --- phase and standing --------------------------------------------------------------------
# shared/phase.ts and shared/import-diagnostic.ts. Heuristics, and named as such wherever a claim
# gets scoped by them.
PIECE_VALUE = {"p": 0, "n": 3, "b": 3, "r": 5, "q": 9, "k": 0}
ENDGAME_MATERIAL_THRESHOLD = 13
OPENING_MAX_PLY = 20
CLEAR_EDGE_CP = 100


def non_pawn_material(board) -> int:
    total = 0
    for _, piece in board.piece_map().items():
        total += PIECE_VALUE[piece.symbol().lower()]
    return total


def classify_phase(board, ply: int) -> str:
    if non_pawn_material(board) <= ENDGAME_MATERIAL_THRESHOLD:
        return "endgame"
    if ply <= OPENING_MAX_PLY:
        return "opening"
    return "middlegame"


def standing_from(eval_before_cp: float) -> str:
    if eval_before_cp >= CLEAR_EDGE_CP:
        return "winning"
    if eval_before_cp <= -CLEAR_EDGE_CP:
        return "losing"
    return "level"


# --- opening book --------------------------------------------------------------------------
# shared/position-key.ts + shared/opening-book.ts, and the 833 keys generated by
# scripts/build_opening_book.ts from the 2026-03 dump -- a month disjoint from every B3 period,
# which tests/test_ports.py asserts rather than assumes.
_BOOK_PATH = os.path.join(os.path.dirname(__file__), "opening_book_keys.json")
with open(_BOOK_PATH) as fh:
    BOOK_KEYS = frozenset(json.load(fh))


def position_key(fen: str) -> str:
    """The four position-determining FEN fields. The counters are a record of the game, not of the
    position, so two knights out and back are the same position."""
    return " ".join(fen.strip().split()[:4])


def book_key(fen: str) -> int:
    """32-bit FNV-1a over `position_key`, exactly as shared/opening-book.ts computes it."""
    h = 0x811C9DC5
    for ch in position_key(fen):
        h ^= ord(ch)
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h


def is_book(fen: str) -> bool:
    return book_key(fen) in BOOK_KEYS


# --- identity ------------------------------------------------------------------------------
def player_hash(username: str) -> str:
    """Stable pseudonym. The plaintext username never reaches a committed artifact."""
    return hashlib.blake2b(username.strip().lower().encode(), digest_size=8).hexdigest()


def unit_hash(seed: int, *parts: str) -> float:
    """A deterministic uniform(0,1) from a seed and some strings.

    Sampling acceptance goes through this rather than through arrival order, so which games are in
    the sample does not depend on where in a 30GB stream they happened to appear, and the whole
    draw is reproducible from the seed alone.
    """
    h = hashlib.blake2b(f"{seed}|{'|'.join(parts)}".encode(), digest_size=8).digest()
    return int.from_bytes(h, "big") / 2**64


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_bytes(chunks: Iterable[bytes]) -> str:
    h = hashlib.sha256()
    for c in chunks:
        h.update(c)
    return h.hexdigest()


# --- rating bands --------------------------------------------------------------------------
RATING_MIN, RATING_MAX = 800, 2600
BAND_WIDTH = 200
BANDS = [(lo, lo + BAND_WIDTH) for lo in range(RATING_MIN, RATING_MAX, BAND_WIDTH)]
BAND_LABELS = [f"{lo}-{hi - 1}" for lo, hi in BANDS]


def rating_band(rating: int) -> str | None:
    """The band label, or None for a rating outside the studied range. Never merged: a band that is
    short of players is reported short, per DATA_PROTOCOL.md."""
    if rating < RATING_MIN or rating >= RATING_MAX:
        return None
    return BAND_LABELS[(rating - RATING_MIN) // BAND_WIDTH]
