/**
 * The anchor set -- the positions every player answers.
 *
 * GENERATED by scripts/build_anchor_set.ts, which carries the sampling rule and the reasoning.
 * Do not edit by hand: a bank that drifts from its generator is a bank whose provenance is a
 * story rather than a record.
 *
 * WHAT IT IS FOR. The calibration gap over a player's own games is not comparable to anyone
 * else's, because it moves with the difficulty of the positions they happened to reach. Held
 * fixed, difficulty variance across players is zero by construction, and what is left is the
 * thing the product claims to measure.
 *
 * PROVENANCE: the Lichess open database (CC0 -- "use them for research, commercial purpose,
 * publication, anything you like"), standard rated games, blitz and slower, terminating normally,
 * carrying engine evaluations. Positions past the opening, not the last ply, and not already
 * decided (|eval| <= 300cp, which is Regan's exclusion). Taken by a fixed stride through
 * the eligible stream rather than chosen, because overconfidence is substantial on SELECTED items
 * and near zero on REPRESENTATIVE ones (Gigerenzer et al. 1991; Juslin 1994) -- a curated bank
 * would manufacture the finding it exists to measure.
 *
 * DIFFICULTY OF THIS BANK, in aggregate only: median |eval| 35cp, and 39 of
 * 60 positions within 50cp of level. Per-position evaluations are NOT here and must
 * never be: R3 forbids engine output reaching the client before a decision is recorded, and a
 * position arriving with its own score attached is exactly that. They were used to exclude
 * decided positions at build time and then discarded.
 *
 * VERSIONED, because changing the bank changes what the number means. A reading taken on one
 * version is not comparable to a reading taken on another, and nothing may silently pool them.
 */

/** Bump whenever the positions change. Readings across versions are not comparable. */
export const ANCHOR_SET_VERSION = 1;

export interface AnchorPosition {
  /** Stable across regenerations: the source game and the half-move within it. */
  id: string;
  fen: string;
}

export const ANCHOR_POSITIONS: readonly AnchorPosition[] = [
  { id: "zIiUzfdJ-21", fen: "r1bq1rk1/3nppbp/p2p1np1/1p6/3BP3/1BN2P2/PPPQN1PP/2KR3R b - - 1 11" },
  { id: "4EIsquEO-21", fen: "r1b2rk1/pp1nqppp/2p2n2/3pP3/2P5/P4NP1/1PQNPPBP/R4RK1 b - - 0 11" },
  { id: "VsTWERzW-22", fen: "r1b2rk1/pp2ppbp/2p3p1/3q4/8/3B3P/PPPP1PP1/R1BQ1RK1 w - - 2 12" },
  { id: "9v9hiJkn-27", fen: "r1qr2k1/pp2ppb1/2p1bnpp/4N3/PnpPP3/2N1B1PP/1P2QPBK/R4R2 b - - 1 14" },
  { id: "eU9aqmOd-24", fen: "r4rk1/p2pppbp/bq4p1/3pP3/5P2/3B4/PPP3PP/R1BQ1R1K w - - 3 13" },
  { id: "mxHLnBem-23", fen: "2rq1rk1/pp1bbpp1/2n1pn1p/3p4/3P4/PPN1PN2/1B2BPPP/2RQ1RK1 b - - 2 12" },
  { id: "5ebnc3ef-32", fen: "2b2rk1/1pN2p1p/8/2r1n3/p1P3p1/P3P3/1P3PPP/3RKB1R w K - 1 17" },
  { id: "55L9t5PX-28", fen: "r2q1rk1/pp1b2p1/2p1p2p/3pPp2/2PP4/3B4/PP1Q1PPP/R4RK1 w - - 0 15" },
  { id: "dq4BOiwR-27", fen: "r1bqk2r/4ppb1/1npp1np1/p6p/PpPPP3/1P1NBP2/3QN1PP/R3KB1R b KQkq c3 0 14" },
  { id: "TLKNt39X-24", fen: "rnbqk1nr/pp3pb1/2ppp3/7p/2PPP1p1/2N1B1N1/PP1QBPP1/1R3RK1 w kq - 2 13" },
  { id: "SzRyxcsO-27", fen: "r3k2r/1p1B1ppp/pq2p3/2bpP2b/8/1QP4P/PP1N1PP1/R1B2RK1 b kq - 0 14" },
  { id: "O4HvpRiU-21", fen: "r2qk2r/pb2bppp/1p1p1n2/4p3/2P1P3/2NQB3/PP2BPPP/R4RK1 b kq - 3 11" },
  { id: "GyrJazw4-21", fen: "r1bq1rk1/p4pbp/2p2np1/np1pp1B1/4P3/2PP1Q2/PPBN1PPP/R3K1NR b KQ - 1 11" },
  { id: "BFtNwzmI-33", fen: "2kr3r/pp1q2p1/2p1pp1p/3p4/3P2P1/2PQPP2/PP4P1/1K1R3R b - - 0 17" },
  { id: "f6UpWIm7-25", fen: "r2q1rk1/pp3pp1/2pbpn1p/5b2/2BP4/2P2N1P/PP2QPP1/R1B1R1K1 b - - 1 13" },
  { id: "0vqdUmWq-24", fen: "r2q1rk1/3nbppp/pp1ppn2/8/3P4/2P2N1P/PP1NQPPB/R4RK1 w - - 0 13" },
  { id: "OsQeXeVi-23", fen: "r3kb1r/1p3ppp/1pn1p3/1B1p4/3P4/4PP2/PP1B1P1P/R3K2R b KQkq - 1 12" },
  { id: "gtiZpLyc-21", fen: "r2qkb1r/pp1bppp1/5n1p/3P4/2Q4B/2N5/PP3PPP/R3K1NR b KQkq - 1 11" },
  { id: "jpIY0ENG-24", fen: "r3k2r/ppqn1ppp/2nbp3/3p2Bb/3P4/2PB1N1P/PP3PP1/R2QRNK1 w kq - 3 13" },
  { id: "02lEXIwV-26", fen: "r4rk1/1ppbnppp/p2p4/8/2BPP3/2N5/PP3PPP/3R1RK1 w - - 0 14" },
  { id: "3iabRgZK-29", fen: "r4rk1/pp1n1pp1/2p1pnp1/q7/PbBP2P1/2N1P2P/1P1BQP2/R2R2K1 b - - 1 15" },
  { id: "6EcT2GTu-23", fen: "r3kb1r/pp3ppp/1qn1p3/4Nb2/3Pp3/7P/PPPQBPP1/R1B2RK1 b kq - 1 12" },
  { id: "CvIXgELb-30", fen: "r1q2rk1/ppp1bppp/8/3Pp3/8/4BQP1/PPP2P1P/R3R1K1 w - - 1 16" },
  { id: "XFaLiOTc-29", fen: "r1bq1rk1/1p1nppbp/3p2p1/3P4/1PP5/2N1B3/4BPPP/2RQ1RK1 b - - 0 15" },
  { id: "6jc8CpTE-26", fen: "r2q2k1/ppp2pp1/2npbn1p/6B1/P7/2PB1N2/1PP2PPP/R3Q1K1 w - - 0 14" },
  { id: "ri7pzjZf-23", fen: "r2q1rk1/pbp1bppp/1p3n2/3Pp3/2P1P3/P1N5/1P2B1PP/R1BQ1RK1 b - - 3 12" },
  { id: "8N2uoNXy-21", fen: "r2q1rk1/p2n1pp1/bp1bpn1p/2pp4/3P3B/2P1PN2/PPBN1PPP/2RQK2R b K - 5 11" },
  { id: "AqV3uoxN-21", fen: "r1bqk2r/pp3pb1/3p1np1/2nPp2p/2P5/2NBBP2/PP1QN1PP/R3K2R b KQkq - 2 11" },
  { id: "IJk1AJLh-22", fen: "r3k2r/3qbppp/p1p1pn2/3p2B1/3P4/2N5/PPP2PPP/R2Q1RK1 w kq - 2 12" },
  { id: "G6pxOOC8-21", fen: "r2q1rk1/ppp3p1/1Nnppn1p/4p3/4P3/P2P1N1P/1PP2PP1/R1BQ1RK1 b - - 0 11" },
  { id: "vIOwCI86-23", fen: "r2q1rk1/p2bbppp/4pn2/1B1p4/8/2N1B3/PPP1QPPP/3R1RK1 b - - 7 12" },
  { id: "sndoIPeU-22", fen: "r3kb1r/ppq2ppp/2p1pnb1/8/6P1/3PBN1P/PPP1QP2/2KR1B1R w kq - 0 12" },
  { id: "bEpwrjz8-23", fen: "r1bq1rk1/p1n2pbp/1p1p1np1/2pP4/P7/2N3P1/1P1NPPBP/R1BQR1K1 b - - 1 12" },
  { id: "wjYO7Akz-23", fen: "r4rk1/pp1n1ppp/2pq4/3p1b2/3PN3/4PN2/PP2BPPP/2RQ1RK1 b - - 0 12" },
  { id: "cKWUK5Uz-24", fen: "r1b2rk1/ppqn1ppp/8/2pp4/3PP3/5Nb1/PP1N1PPP/R2Q1RK1 w - - 0 13" },
  { id: "GZxGnO3d-21", fen: "r1b1kn1r/ppq1bpp1/2n1p2p/2ppP2P/8/2P2NP1/PP1PQPB1/RNB1R1K1 b kq - 0 11" },
  { id: "WG3ilBhI-27", fen: "r3r1k1/1pqn1pbp/2pp1np1/p3p3/2PPP3/1P3QPP/PB1N1PB1/2RR2K1 b - - 3 14" },
  { id: "Oj9fbmhB-25", fen: "rn1q1rk1/pp3ppp/2p5/b2pPp2/3P1P2/1PP5/P1Q3PP/RNB2RK1 b - - 2 13" },
  { id: "xMreLEhX-21", fen: "r2q1rk1/pp3ppp/2n2n2/2bp4/6b1/1P1B1N1P/PBPN1PP1/R2Q1RK1 b - - 0 11" },
  { id: "BH6uDnfG-28", fen: "r3r1k1/pp1qbppp/1np2n2/1P1p4/3P1B2/P1NQP3/3N1PPP/R4RK1 w - - 1 15" },
  { id: "WvD0ivsj-25", fen: "r1bq1rk1/1pp2pb1/3p1npp/p1nPp3/2P1P3/P1N1BN1P/1PB2PP1/R2Q1RK1 b - - 0 13" },
  { id: "FnF1rUln-29", fen: "r2q1rk1/ppbn1pp1/2p2np1/2Pp4/1P1B4/5PP1/P2NP1BP/R2Q1RK1 b - - 0 15" },
  { id: "6YQYsrKB-25", fen: "r1b1k2r/p2nppb1/2p3p1/qpNp2Bp/3P3P/2P1P3/PP2BPP1/R2Q1RK1 b kq - 1 13" },
  { id: "vumOR6dS-21", fen: "2rqkb1r/1p1n1pp1/p2pbn2/4p2p/4P3/1NN1BP2/PPPQB1PP/2KR3R b k - 5 11" },
  { id: "e4I4nvYZ-22", fen: "r1bq1rk1/p3bppp/1pn1pn2/8/2BP4/P1N2N1P/1P3PP1/R1BQ1RK1 w - - 0 12" },
  { id: "0KphEjRL-23", fen: "r2q1rk1/pb1nppbp/2n3p1/1pp5/3pP3/P2P1NP1/1PP1BP1P/1RBQRNK1 b - - 0 12" },
  { id: "H8tptuM6-21", fen: "rn1q1rk1/pbnpbppp/1pp5/5N2/4P3/6P1/PP3PBP/RNBQ1RK1 b - - 0 11" },
  { id: "Dvtjsi7f-21", fen: "r1bq1rk1/pp1nnppp/4p3/2p5/2PP4/3BPN2/P2B1PPP/R2Q1RK1 b - - 1 11" },
  { id: "eBg60vkw-21", fen: "r1bq2k1/ppp1n1bp/2np2p1/4p3/2PN1r2/PPN5/1B1PBPPP/R2Q1RK1 b - - 1 11" },
  { id: "lDAdR8VV-21", fen: "rn1qk2r/pp2bpp1/2p1pn1p/3p3P/3P1BP1/P1NQPP2/1PP5/R3K1NR b KQkq - 0 11" },
  { id: "ec2IUJFC-21", fen: "rn3rk1/pp2bppp/1qp2n2/3p2B1/3P4/2NBP2P/PP2QPP1/R3K2R b KQ - 2 11" },
  { id: "xOP5nkTv-21", fen: "r3k2r/1p1q1ppp/p1nbpn2/3p2B1/3P4/2P5/PP2BPPP/RN1Q1RK1 b kq - 2 11" },
  { id: "4PqtDoQ4-21", fen: "r2qk2r/1p1nbppp/p3pn2/3pB3/3P4/2PQ1N2/PP1N1PPP/R4RK1 b kq - 7 11" },
  { id: "b5ZS6okq-21", fen: "r1bq1rk1/ppp2ppp/3b1n2/3p4/8/1PPBPN2/P4PPP/R1BQ1RK1 b - - 0 11" },
  { id: "yIdpRZ65-21", fen: "r1bq1rk1/p3bppp/2pp1n2/np6/3QP3/PBN1BN2/1PP2PPP/R4RK1 b - - 0 11" },
  { id: "9GOdINGR-21", fen: "r1b2rk1/ppqnbppp/2pp1n2/4p1N1/P1BPP3/1PN4P/2P2PP1/R1BQR1K1 b - - 0 11" },
  { id: "Yj0QrmkE-21", fen: "r1b2rk1/ppp2ppp/3p1q2/4n3/4PP2/2NB4/PPP3PP/R2Q1RK1 b - - 0 11" },
  { id: "qmLMHHdQ-21", fen: "r1bq1rk1/p3ppbp/1p1p1np1/8/3P1B2/2PB4/PP1NQPPP/R4RK1 b - - 0 11" },
  { id: "5URkl0Zo-21", fen: "rb1qk2r/pp3ppp/2N1pnb1/3p4/8/P4NP1/1P1PPPBP/R1BQ1RK1 b kq - 0 11" },
  { id: "VXxQzKmj-21", fen: "r2qk2r/p3ppbp/2p2np1/3p4/3P1B2/2N4P/PPP2PP1/R2QK2R b KQkq - 0 11" },
];

const BY_FEN = new Set(ANCHOR_POSITIONS.map((position) => position.fen));

/**
 * Whether a decision was taken on a bank position.
 *
 * By FEN rather than by a stored flag, on purpose: it is retroactive, it needs no column, and it
 * cannot go stale against the bank. A position is in the set or it is not, and the FEN is the
 * whole of what makes that true.
 */
export function isAnchorFen(fen: string): boolean {
  return BY_FEN.has(fen);
}
