/**
 * The moves that lead to each anchor position.
 *
 * GENERATED by scripts/build_anchor_set.ts alongside shared/anchor-set.ts. Separate from it for
 * one reason: `isAnchorFen` is reached from code every arrival loads, and these move lists are
 * needed only when a position is actually SERVED. Fifteen kilobytes of movetext in the entry
 * bundle to answer a membership test is fifteen kilobytes nobody asked for.
 *
 * Import this lazily. The two files are generated together and tests/shared/anchor-set.test.ts
 * holds them in lockstep, so the split cannot become a drift.
 */

export interface AnchorMoves {
  id: string;
  /**
   * The half-move the board shows -- the position BEFORE the decision.
   *
   * The board renders currentPly as "the last move played", so the decision is taken on the
   * position that follows it.
   */
  ply: number;
  /**
   * The moves leading to it, in SAN, so the position arrives with the game that produced it
   * rather than as a bare diagram. Trimmed to before the move under decision: one ply more and
   * the answer would be on screen beside the question.
   */
  sans: readonly string[];
}

export const ANCHOR_MOVES: readonly AnchorMoves[] = [
  { id: "zIiUzfdJ-21", ply: 20, sans: ["d4", "d6", "Nc3", "g6", "e4", "Bg7", "f3", "Nd7", "Be3", "c5", "Bc4", "cxd4", "Bxd4", "Ngf6", "Nge2", "O-O", "Qd2", "a6", "Bb3", "b5", "O-O-O"] },
  { id: "4EIsquEO-21", ply: 20, sans: ["d4", "Nf6", "c4", "e6", "g3", "Bb4+", "Bd2", "Qe7", "a3", "Bxd2+", "Nxd2", "d5", "Bg2", "Nbd7", "Ngf3", "O-O", "O-O", "c6", "Qc2", "e5", "dxe5"] },
  { id: "VsTWERzW-22", ply: 21, sans: ["e4", "d6", "Nf3", "Nf6", "e5", "dxe5", "Nxe5", "Nbd7", "Nxd7", "Qxd7", "Nc3", "g6", "h3", "Bg7", "Bb5", "c6", "Bd3", "Nd5", "Nxd5", "Qxd5", "O-O", "O-O"] },
  { id: "9v9hiJkn-27", ply: 26, sans: ["Nf3", "d5", "g3", "g6", "Bg2", "Bg7", "d4", "Nf6", "O-O", "O-O", "c4", "c6", "a4", "Be6", "Nc3", "dxc4", "e4", "Na6", "h3", "Nb4", "Be3", "Qc8", "Kh2", "Rd8", "Qe2", "h6", "Ne5"] },
  { id: "eU9aqmOd-24", ply: 23, sans: ["e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "Nf6", "Nxc6", "bxc6", "Bd3", "g6", "O-O", "Bg7", "Nc3", "O-O", "e5", "Nd5", "Nxd5", "cxd5", "f4", "Qb6+", "Kh1", "Ba6"] },
  { id: "mxHLnBem-23", ply: 22, sans: ["d4", "Nf6", "c4", "e6", "Nc3", "d5", "Nf3", "c6", "e3", "Be7", "Be2", "O-O", "O-O", "h6", "cxd5", "cxd5", "b3", "Nc6", "Bb2", "Bd7", "a3", "Rc8", "Rc1"] },
  { id: "5ebnc3ef-32", ply: 31, sans: ["d4", "d5", "c4", "e5", "dxe5", "d4", "Nf3", "Nc6", "a3", "a5", "Nbd2", "g5", "Nb3", "g4", "Bg5", "Be7", "Bxe7", "Ngxe7", "Nfxd4", "a4", "Nxc6", "Qxd1+", "Rxd1", "Nxc6", "Nd4", "Nxe5", "Nb5", "O-O", "Nxc7", "Ra5", "e3", "Rc5"] },
  { id: "55L9t5PX-28", ply: 27, sans: ["d4", "d5", "Bf4", "e6", "e3", "Nf6", "Nf3", "Bd6", "Bd3", "Bxf4", "exf4", "Ne4", "c3", "O-O", "Qc2", "f5", "O-O", "Nc6", "Ne5", "Nxe5", "fxe5", "Bd7", "Nd2", "Nxd2", "Qxd2", "h6", "c4", "c6"] },
  { id: "dq4BOiwR-27", ply: 26, sans: ["e4", "d6", "d4", "Nf6", "Nc3", "g6", "Bg5", "h6", "Be3", "a6", "Qd2", "b5", "f3", "Bg7", "Nge2", "Nbd7", "Nf4", "c6", "Nd3", "Nb6", "b3", "a5", "a4", "b4", "Ne2", "h5", "c4"] },
  { id: "TLKNt39X-24", ply: 23, sans: ["e4", "d6", "d4", "c6", "c4", "Qb6", "Nc3", "h6", "Rb1", "g5", "Be3", "Bg7", "h4", "g4", "Nge2", "h5", "Ng3", "e6", "Be2", "Qd8", "O-O", "Qxh4", "Qd2", "Qd8"] },
  { id: "SzRyxcsO-27", ply: 26, sans: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "Bd3", "Nf6", "c3", "Bg4", "Qb3", "Qb6", "Nd2", "Nbd7", "h3", "Bh5", "Ngf3", "e6", "Ne5", "Nxe5", "dxe5", "Nd7", "Bb5", "Bc5", "O-O", "a6", "Bxd7+"] },
  { id: "O4HvpRiU-21", ply: 20, sans: ["e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "d6", "c4", "Nf6", "Nc3", "Nxd4", "Qxd4", "b6", "Be2", "Bb7", "Be3", "e5", "Qd3", "Be7", "O-O"] },
  { id: "GyrJazw4-21", ply: 20, sans: ["e4", "e5", "Qh5", "Nc6", "Bc4", "g6", "Qf3", "Nf6", "c3", "Bg7", "d3", "O-O", "Bg5", "Na5", "Bb5", "c6", "Ba4", "b5", "Bc2", "d5", "Nd2"] },
  { id: "BFtNwzmI-33", ply: 32, sans: ["d4", "Nf6", "Nf3", "d5", "Bf4", "Bf5", "e3", "c6", "c3", "e6", "Ne5", "Nbd7", "Nd2", "Ne4", "Nxe4", "Bxe4", "f3", "Bg6", "Bd3", "Bxd3", "Qxd3", "f6", "Nxd7", "Qxd7", "Bg3", "Bd6", "O-O-O", "O-O-O", "Kb1", "Bxg3", "hxg3", "h6", "g4"] },
  { id: "f6UpWIm7-25", ply: 24, sans: ["e4", "c6", "Nc3", "d5", "Nf3", "dxe4", "Nxe4", "Nf6", "Qe2", "Nxe4", "Qxe4", "Nd7", "Bc4", "Nf6", "Qe2", "Bf5", "d4", "e6", "O-O", "Bd6", "c3", "O-O", "h3", "h6", "Re1"] },
  { id: "0vqdUmWq-24", ply: 23, sans: ["d4", "e6", "Nf3", "Nf6", "Bf4", "c5", "e3", "cxd4", "exd4", "Be7", "c3", "b6", "Be2", "O-O", "O-O", "Ba6", "h3", "Bxe2", "Qxe2", "d6", "Nbd2", "Nbd7", "Bh2", "a6"] },
  { id: "OsQeXeVi-23", ply: 22, sans: ["c4", "c6", "Nc3", "Nf6", "e3", "d5", "Nf3", "Bg4", "Qb3", "Qb6", "Qxb6", "axb6", "cxd5", "Bxf3", "gxf3", "Nxd5", "Nxd5", "cxd5", "d4", "Nc6", "Bd2", "e6", "Bb5"] },
  { id: "gtiZpLyc-21", ply: 20, sans: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "c4", "Nf6", "Nc3", "Nc6", "Bg5", "dxc4", "d5", "Na5", "Bxc4", "Nxc4", "Qa4+", "Bd7", "Qxc4", "h6", "Bh4"] },
  { id: "jpIY0ENG-24", ply: 23, sans: ["e4", "c6", "Nf3", "d5", "exd5", "cxd5", "d4", "Nc6", "c3", "Nf6", "Bd3", "Bg4", "O-O", "e6", "Nbd2", "Bd6", "Re1", "Qb6", "Nf1", "Qc7", "h3", "Bh5", "Bg5", "Nd7"] },
  { id: "02lEXIwV-26", ply: 25, sans: ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Bc5", "Be3", "Bxd4", "Bxd4", "Nxd4", "Qxd4", "Qf6", "c3", "d6", "Bc4", "Bd7", "O-O", "Qxd4", "cxd4", "Ne7", "Nc3", "O-O", "Rad1", "a6"] },
  { id: "3iabRgZK-29", ply: 28, sans: ["d4", "d5", "Nf3", "Nf6", "c4", "c6", "Nc3", "dxc4", "a4", "Bf5", "e3", "e6", "Bxc4", "Bb4", "O-O", "O-O", "Qe2", "Bg6", "h3", "Bh5", "Rd1", "Nbd7", "g4", "Bg6", "Nh4", "Qa5", "Nxg6", "hxg6", "Bd2"] },
  { id: "6EcT2GTu-23", ply: 22, sans: ["e4", "c6", "Nf3", "d5", "exd5", "cxd5", "d4", "Nf6", "Nc3", "Bg4", "Be2", "Nc6", "Qd3", "e6", "h3", "Bf5", "Qd2", "Qb6", "O-O", "Ne4", "Nxe4", "dxe4", "Ne5"] },
  { id: "CvIXgELb-30", ply: 29, sans: ["e4", "e5", "Nf3", "Nc6", "Nc3", "Nf6", "g3", "d6", "Bg2", "Bg4", "O-O", "Be7", "d3", "Nd4", "Be3", "Nxf3+", "Bxf3", "Bh3", "Re1", "Qc8", "d4", "Bg4", "dxe5", "dxe5", "Nd5", "Bxf3", "Qxf3", "Nxd5", "exd5", "O-O"] },
  { id: "XFaLiOTc-29", ply: 28, sans: ["c4", "c5", "Nf3", "Nc6", "Nc3", "g6", "e3", "Bg7", "d4", "cxd4", "exd4", "d6", "d5", "Ne5", "Nxe5", "Bxe5", "Be2", "Bg7", "O-O", "Nf6", "Be3", "O-O", "Rc1", "Nd7", "b4", "a5", "a3", "axb4", "axb4"] },
  { id: "6jc8CpTE-26", ply: 25, sans: ["e4", "e5", "Nf3", "Nf6", "Nc3", "Bb4", "Nxe5", "O-O", "Bc4", "Bxc3", "dxc3", "d6", "Nf3", "Re8", "O-O", "Rxe4", "Bd3", "Re8", "Re1", "Rxe1+", "Qxe1", "Nc6", "Bg5", "Be6", "a4", "h6"] },
  { id: "ri7pzjZf-23", ply: 22, sans: ["d4", "e6", "c4", "Nf6", "a3", "Be7", "Nc3", "b6", "e4", "Bb7", "d5", "d6", "f4", "Nbd7", "Nf3", "e5", "fxe5", "Nxe5", "Nxe5", "dxe5", "Be2", "O-O", "O-O"] },
  { id: "8N2uoNXy-21", ply: 20, sans: ["d4", "Nf6", "Bf4", "e6", "e3", "d5", "Nd2", "c5", "c3", "Bd6", "Bg5", "h6", "Bh4", "Nbd7", "Ngf3", "b6", "Bd3", "O-O", "Bc2", "Ba6", "Rc1"] },
  { id: "AqV3uoxN-21", ply: 20, sans: ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "f3", "c6", "Be3", "Nbd7", "Qd2", "h5", "Bd3", "e5", "d5", "cxd5", "exd5", "Nc5", "Nge2"] },
  { id: "IJk1AJLh-22", ply: 21, sans: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "Nc3", "Nc6", "Nf3", "Nf6", "Bb5", "e6", "Ne5", "Bd7", "Nxd7", "Qxd7", "O-O", "a6", "Bxc6", "bxc6", "Bg5", "Be7"] },
  { id: "G6pxOOC8-21", ply: 20, sans: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Nc3", "Bc5", "d3", "h6", "a3", "d6", "h3", "O-O", "O-O", "Be6", "Bxe6", "fxe6", "Na4", "Bb6", "Nxb6"] },
  { id: "vIOwCI86-23", ply: 22, sans: ["e4", "c5", "Nf3", "e6", "d4", "cxd4", "Nxd4", "Nc6", "Be3", "Nf6", "Nxc6", "bxc6", "Nc3", "d5", "exd5", "cxd5", "Bb5+", "Bd7", "Qe2", "Be7", "O-O", "O-O", "Rad1"] },
  { id: "sndoIPeU-22", ply: 21, sans: ["e4", "c6", "Nf3", "d5", "d3", "Qc7", "Nc3", "dxe4", "Nxe4", "Bg4", "h3", "Bh5", "Be3", "Nd7", "g4", "Bg6", "Qe2", "Ngf6", "Nxf6+", "Nxf6", "O-O-O", "e6"] },
  { id: "bEpwrjz8-23", ply: 22, sans: ["d4", "Nf6", "c4", "e6", "g3", "c5", "d5", "exd5", "cxd5", "d6", "Bg2", "g6", "Nf3", "Bg7", "O-O", "O-O", "Nc3", "Na6", "Nd2", "Nc7", "a4", "b6", "Re1"] },
  { id: "wjYO7Akz-23", ply: 22, sans: ["d4", "d5", "Bf4", "Nf6", "e3", "Bf5", "c4", "e6", "Nc3", "Bd6", "Bxd6", "Qxd6", "Nf3", "c6", "cxd5", "exd5", "Be2", "Nbd7", "Rc1", "O-O", "O-O", "Ne4", "Nxe4"] },
  { id: "cKWUK5Uz-24", ply: 23, sans: ["d4", "d5", "Bf4", "e6", "Nf3", "Bd6", "Bg3", "Nf6", "e3", "c5", "Nbd2", "Qc7", "c3", "Nbd7", "Bb5", "O-O", "Bxd7", "Nxd7", "O-O", "e5", "e4", "exd4", "cxd4", "Bxg3"] },
  { id: "GZxGnO3d-21", ply: 20, sans: ["e4", "e6", "Nf3", "d5", "e5", "c5", "g3", "Nc6", "Bg2", "Nge7", "O-O", "Ng6", "Re1", "Qc7", "Qe2", "Be7", "h4", "h6", "h5", "Nf8", "c3"] },
  { id: "WG3ilBhI-27", ply: 26, sans: ["Nf3", "Nf6", "b3", "g6", "Bb2", "Bg7", "g3", "d6", "d4", "Bg4", "Bg2", "c6", "O-O", "O-O", "Nbd2", "Nbd7", "e4", "e5", "h3", "Bxf3", "Qxf3", "Qc7", "c4", "a5", "Rac1", "Rfe8", "Rfd1"] },
  { id: "Oj9fbmhB-25", ply: 24, sans: ["e4", "c6", "f4", "d5", "e5", "Bf5", "Nf3", "e6", "d4", "Bb4+", "c3", "Ba5", "Bd3", "Bg6", "O-O", "Ne7", "Nh4", "Nf5", "Nxf5", "Bxf5", "Bxf5", "exf5", "b3", "O-O", "Qc2"] },
  { id: "xMreLEhX-21", ply: 20, sans: ["e4", "e6", "b3", "d5", "Bb2", "c5", "exd5", "exd5", "Nf3", "Nf6", "d4", "Bd6", "dxc5", "Bxc5", "Bd3", "O-O", "O-O", "Bg4", "Nbd2", "Nc6", "h3"] },
  { id: "BH6uDnfG-28", ply: 27, sans: ["d4", "c6", "c4", "d5", "Nc3", "Nf6", "Bf4", "e6", "cxd5", "exd5", "e3", "Bf5", "Bd3", "Bxd3", "Qxd3", "Bb4", "a3", "Be7", "Nf3", "O-O", "O-O", "Nbd7", "b4", "Nb6", "Nd2", "Re8", "b5", "Qd7"] },
  { id: "WvD0ivsj-25", ply: 24, sans: ["e3", "g6", "d4", "Bg7", "c4", "Nf6", "Nc3", "O-O", "Nf3", "d6", "Bd3", "Nc6", "d5", "Nb8", "O-O", "e5", "e4", "h6", "h3", "Na6", "Be3", "Nc5", "Bc2", "a5", "a3"] },
  { id: "FnF1rUln-29", ply: 28, sans: ["Nf3", "d5", "g3", "Bg4", "Bg2", "c6", "d4", "e6", "O-O", "Nf6", "b3", "Bd6", "Bb2", "Nbd7", "c4", "O-O", "Ne5", "Bh5", "f3", "Bg6", "Nxg6", "hxg6", "c5", "Bc7", "b4", "e5", "Nd2", "exd4", "Bxd4"] },
  { id: "6YQYsrKB-25", ply: 24, sans: ["d4", "Nf6", "Nc3", "d5", "Bf4", "c6", "e3", "g6", "Be2", "Bg7", "h4", "h5", "Nf3", "Qb6", "Na4", "Qa5+", "c3", "Nbd7", "O-O", "Ne4", "Ng5", "Nxg5", "Bxg5", "b5", "Nc5"] },
  { id: "vumOR6dS-21", ply: 20, sans: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "a6", "f3", "e5", "Nb3", "Be6", "Be3", "h5", "Qd2", "Nbd7", "Be2", "Rc8", "O-O-O"] },
  { id: "e4I4nvYZ-22", ply: 21, sans: ["e4", "c6", "c4", "d5", "cxd5", "cxd5", "exd5", "Qxd5", "Nc3", "Qd8", "Nf3", "Nc6", "Bc4", "Nf6", "h3", "e6", "a3", "Be7", "O-O", "O-O", "d4", "b6"] },
  { id: "0KphEjRL-23", ply: 22, sans: ["e3", "c5", "Nf3", "Nf6", "Be2", "g6", "O-O", "Bg7", "d3", "d5", "Nbd2", "Nc6", "a3", "O-O", "Rb1", "b5", "Re1", "Bb7", "Nf1", "d4", "e4", "Nd7", "g3"] },
  { id: "H8tptuM6-21", ply: 20, sans: ["d4", "Nf6", "c4", "e6", "Nf3", "b6", "g3", "Bb7", "Bg2", "Be7", "O-O", "O-O", "d5", "exd5", "Nh4", "c6", "cxd5", "Nxd5", "Nf5", "Nc7", "e4"] },
  { id: "Dvtjsi7f-21", ply: 20, sans: ["d4", "d5", "c4", "e6", "Nc3", "Bb4", "cxd5", "Qxd5", "e3", "Ne7", "Bd2", "Bxc3", "bxc3", "O-O", "c4", "Qd8", "Nf3", "Nd7", "Bd3", "c5", "O-O"] },
  { id: "eBg60vkw-21", ply: 20, sans: ["e3", "d6", "c4", "g6", "b3", "Bg7", "Nc3", "e5", "Bb2", "Nc6", "Nf3", "Nge7", "Be2", "O-O", "O-O", "f5", "a3", "f4", "exf4", "Rxf4", "Nd4"] },
  { id: "lDAdR8VV-21", ply: 20, sans: ["d4", "c6", "Nc3", "d5", "Bf4", "Bf5", "e3", "Nf6", "f3", "e6", "g4", "Bg6", "h4", "h6", "h5", "Bh7", "Bd3", "Bxd3", "Qxd3", "Be7", "a3"] },
  { id: "ec2IUJFC-21", ply: 20, sans: ["d4", "d5", "c4", "c6", "Nc3", "Nf6", "Nf3", "e6", "Bg5", "Be7", "e3", "O-O", "cxd5", "exd5", "Bd3", "Bg4", "h3", "Bxf3", "Qxf3", "Qb6", "Qe2"] },
  { id: "xOP5nkTv-21", ply: 20, sans: ["e4", "c6", "Nf3", "d5", "exd5", "cxd5", "d4", "Nf6", "Bb5+", "Nc6", "Ne5", "Bd7", "Nxd7", "Qxd7", "O-O", "a6", "Be2", "e6", "c3", "Bd6", "Bg5"] },
  { id: "4PqtDoQ4-21", ply: 20, sans: ["e4", "c6", "Nf3", "d5", "exd5", "cxd5", "d4", "Bf5", "Bd3", "Bxd3", "Qxd3", "a6", "c3", "e6", "Bf4", "Nf6", "Be5", "Be7", "O-O", "Nbd7", "Nbd2"] },
  { id: "b5ZS6okq-21", ply: 20, sans: ["d4", "Nf6", "Nd2", "d5", "c3", "e6", "Ngf3", "Nbd7", "e3", "Bd6", "Bd3", "e5", "dxe5", "Nxe5", "Nxe5", "Bxe5", "Nf3", "Bd6", "O-O", "O-O", "b3"] },
  { id: "yIdpRZ65-21", ply: 20, sans: ["e4", "e5", "Nf3", "d6", "Nc3", "Be7", "Bc4", "Nf6", "O-O", "O-O", "d3", "Nc6", "Be3", "Na5", "Bb3", "c6", "d4", "exd4", "Qxd4", "b5", "a3"] },
  { id: "9GOdINGR-21", ply: 20, sans: ["e4", "d6", "d4", "Nf6", "Nc3", "Nbd7", "Nf3", "e5", "Bc4", "Be7", "O-O", "O-O", "Re1", "c6", "a4", "Qc7", "h3", "Re8", "Ng5", "Rf8", "b3"] },
  { id: "Yj0QrmkE-21", ply: 20, sans: ["e4", "e5", "Ne2", "Nc6", "Nbc3", "Nf6", "d4", "exd4", "Nxd4", "Bc5", "Be3", "Bxd4", "Bxd4", "O-O", "Bxf6", "Qxf6", "Bd3", "d6", "O-O", "Ne5", "f4"] },
  { id: "qmLMHHdQ-21", ply: 20, sans: ["d4", "d6", "Bf4", "g6", "e3", "Bg7", "Nf3", "Nf6", "c3", "b6", "Nbd2", "c5", "Bd3", "O-O", "Qe2", "Nc6", "O-O", "cxd4", "Nxd4", "Nxd4", "exd4"] },
  { id: "5URkl0Zo-21", ply: 20, sans: ["c4", "c6", "g3", "d5", "cxd5", "cxd5", "Nf3", "Nf6", "Bg2", "Bf5", "O-O", "e6", "Nc3", "Nc6", "a3", "Bd6", "Nb5", "Bb8", "Nbd4", "Bg6", "Nxc6"] },
  { id: "VXxQzKmj-21", ply: 20, sans: ["e4", "c6", "d4", "d5", "exd5", "cxd5", "Nc3", "Nf6", "Nf3", "Nc6", "Bb5", "Bd7", "Bxc6", "Bxc6", "Bf4", "g6", "Ne5", "Bg7", "Nxc6", "bxc6", "h3"] },
];
