/**
 * Positions a player arrives at prepared, measured rather than asserted.
 *
 * GENERATED by scripts/build_opening_book.ts. Do not edit by hand.
 *
 * A position is here when at least 0.10% of 73,279 real Lichess games -- one in
 * 1,000 -- reached it within the first 30 plies. The rule was fixed before its effect on any
 * accuracy rate was computed, and the effect is reported in docs/MEASUREMENTS.md.
 *
 * WHAT IT IS NOT. Not a claim that these positions are easy, and not a claim about the move the
 * player chose: a player who leaves theory here has made a decision. It is a claim about the
 * POSITION -- that reaching it is common enough that arriving prepared is the norm -- which is
 * what the accuracy rate's denominator needs, because conditioning on the player's move would
 * condition on the outcome.
 *
 * Keys are 32-bit FNV-1a over `positionKey`, so a transposition into a book position is the same
 * entry and the two FEN fields that are a record of the GAME are dropped. Measured on the
 * ${counts.size.toLocaleString("en-US")} distinct positions this corpus produced: ${collisions} collisions with a book key.
 *
 * At half this rate the book would hold 1,732 positions; at double it, 408.
 */
export const BOOK_PROVENANCE = {
  "source": "https://database.lichess.org/standard/lichess_db_standard_rated_2026-03.pgn.zst",
  "month": "2026-03",
  "prefixBytes": 24000000,
  "games": 73279,
  "distinctPositions": 1522179,
  "maxBookPly": 30,
  "bookShare": 0.001,
  "bookPositions": 833,
  "keyCollisionsOnCorpus": 0,
  "sensitivity": {
    "0.0005": 1732,
    "0.002": 408
  }
} as const;
