/**
 * How much a game's phase says about how hard a position is FOR A PERSON.
 *
 * GENERATED by scripts/build_phase_difficulty_reference.ts from the Lichess puzzle database
 * (CC0), which carries a Glicko rating per position derived from real human solve attempts. Do
 * not edit by hand.
 *
 * THE NUMBER THAT MATTERS IS THE LAST ONE. Across 4,416,361 human-rated
 * positions, the phase label explains 0.35% of the variance in
 * difficulty. The product's own corpus finds a real and large difference between phases on its
 * accuracy rule -- and that difference turns out to be almost entirely a property of the rule,
 * not of how hard the positions are for people.
 *
 * WHAT THIS IS NOT. A puzzle rating measures finding a unique winning move in a SELECTED tactical
 * position; the product's accuracy rate measures not losing 30 centipawns on an ORDINARY move.
 * The two magnitudes are not commensurable and must never be subtracted. What is carried here is
 * a statement made entirely inside the puzzle corpus: how much the phase label explains.
 *
 * Filter: RatingDeviation <= 100, NbPlays >= 100, exactly one phase
 * tag. 6,100,960 rows read.
 */

/** Bump when the corpus or the filter changes. Readings across versions are not comparable. */
export const PHASE_DIFFICULTY_VERSION = 1;

/** Human-rated positions behind the figure below. */
export const PHASE_DIFFICULTY_N = 4416361;

/**
 * eta-squared: the share of variance in human-measured difficulty explained by the phase label.
 *
 * Reported to four places because the whole point is how SMALL it is, and rounding it to two
 * would print 0.00 and read as "not measured" rather than "measured, and nearly nothing".
 */
export const PHASE_VARIANCE_EXPLAINED = 0.0035;

export interface PhaseDifficulty {
  phase: string;
  /** Human solve difficulty, in Glicko rating points. Higher is harder. */
  median: number;
  sd: number;
  n: number;
}

/** Easiest first, by median. */
export const PHASE_DIFFICULTY: readonly PhaseDifficulty[] = [
  {
    "phase": "opening",
    "n": 224949,
    "median": 1355,
    "sd": 455
  },
  {
    "phase": "endgame",
    "n": 2171279,
    "median": 1390,
    "sd": 514
  },
  {
    "phase": "middlegame",
    "n": 2020133,
    "median": 1475,
    "sd": 493
  }
];

/** Null rather than a default: a phase the corpus does not rate is not a phase rated zero. */
export function phaseDifficulty(phase: string): PhaseDifficulty | null {
  return PHASE_DIFFICULTY.find((row) => row.phase === phase) ?? null;
}
