/**
 * How accurate everybody is, per bucket. GENERATED by scripts/build_population_baseline.ts.
 *
 * WHAT IT IS FOR. A bucket's accuracy is mostly a property of the bucket. Measured here: people
 * think longer because the position is hard, so the slow bucket is less accurate for EVERYONE,
 * and telling a player that is telling them a fact about chess in the second person. Against this
 * baseline the same figure becomes a statement about them.
 *
 * Built with the product's own definitions -- `classifyPhase`, `BUCKETINGS`,
 * `ACCURATE_WIN_PROBABILITY_LOSS` -- because a baseline computed with its own idea of "accurate"
 * would be a number from a different instrument.
 *
 * NO CONFIDENCE HALF, and there never can be one from imported games: nobody asked those players
 * how sure they were. This baselines accuracy and nothing else.
 *
 * Corpus: Lichess open database (CC0), games with [%eval] and [%clk], terminating normally, base
 * time 180s or more, positions not already decided (|eval| <= 300cp).
 * 693,130 scored moves.
 *
 * A BUCKET THE CORPUS CANNOT SUPPORT IS ABSENT, not zero and not guessed. 500 moves
 * on each side is the floor, and buckets below it are left out entirely -- `populationBucket`
 * returns null for them and a caller must render that as "no baseline" rather than as a
 * comparison. Which buckets those are is a property of the corpus and is expected to change.
 */

/** Bump when the corpus or the rules change. Readings across versions are not comparable. */
export const POPULATION_BASELINE_VERSION = 1;

/** How many moves the baseline was built from. Carried so a caller can report its denominator. */
export const POPULATION_BASELINE_N = 693130;

export interface PopulationBucket {
  key: string;
  /** Share of moves in this bucket the population played accurately. */
  accuracy: number;
  n: number;
  /** The same, for everything OUTSIDE the bucket -- the comparison the detector actually makes. */
  outsideAccuracy: number;
  outsideN: number;
}

export const POPULATION_BASELINE: readonly PopulationBucket[] = [
  { key: "fast-under-45s", accuracy: 0.65233, n: 679036, outsideAccuracy: 0.48482, outsideN: 14094 },
  { key: "slow-over-2m", accuracy: 0.50715, n: 1189, outsideAccuracy: 0.64917, outsideN: 691941 },
  { key: "phase-opening", accuracy: 0.70283, n: 322254, outsideAccuracy: 0.60208, outsideN: 370876 },
  { key: "phase-middlegame", accuracy: 0.58421, n: 337756, outsideAccuracy: 0.71043, outsideN: 355374 },
  { key: "phase-endgame", accuracy: 0.78430, n: 33120, outsideAccuracy: 0.64213, outsideN: 660010 },
  { key: "clock-under-1m", accuracy: 0.66723, n: 29209, outsideAccuracy: 0.64812, outsideN: 663921 },
];

const BY_KEY = new Map(POPULATION_BASELINE.map((bucket) => [bucket.key, bucket]));

/**
 * The population's rates for one bucket, or null when the corpus has none.
 *
 * Null is a real answer, and callers must render it as "no baseline" rather than as a comparison
 * against zero. Every bucket the detector uses cleared the floor in THIS corpus, so nothing
 * returns null today -- but which buckets a corpus can support is a property of the corpus, and
 * a bucket that thins out in the next one must go absent rather than be filled in.
 */
export function populationBucket(key: string): PopulationBucket | null {
  return BY_KEY.get(key) ?? null;
}
