/**
 * What metacognitive sensitivity looks like in the research literature. GENERATED by
 * scripts/build_sensitivity_reference.ts.
 *
 * WHAT IT IS FOR. An AUROC2 of 0.71 is uninterpretable on its own: nobody knows whether that is
 * good. Measured here on 6,570 individual people across 132 datasets of the
 * Confidence Database (Rahnev et al., *Nature Human Behaviour* 4, 317-325, 2020; osf.io/s46pr,
 * CC0), each person's AUROC2 computed by THIS PRODUCT'S OWN \`metacognitiveSensitivity\` under its
 * own \`MIN_BUCKET_N\` floor on both outcomes.
 *
 * CONDITIONED ON FIRST-ORDER ACCURACY, because that turned out to be the dominant term rather
 * than a caveat. Spearman rho between a person's accuracy and their AUROC2 is
 * 0.59 across 3,836 people. An unconditioned band would tell a strong
 * player they are metacognitively gifted for being good at chess, which is the same confound the
 * population baseline exists to remove from the buckets.
 *
 * A BAND, NEVER A PERCENTILE RANK. The literature's task is not this instrument's task: nearly
 * every dataset is a binary or near-binary perceptual or memory judgement, and choosing a move
 * from thirty legal options is not one. Conditioning on accuracy narrows that mismatch and does
 * not close it, so what this supports is one honest sentence -- "among people about this accurate,
 * in the research literature, this number runs from X to Y" -- and nothing stronger. A percentile
 * rank would assert that a chess player and a psychophysics subject are draws from one
 * population, which is exactly the claim the data cannot support.
 *
 * SCALE REGIME. AUROC2 reads only the ORDER of confidence values, so it does not care what a
 * study called its scale -- but it does care how many rungs the scale has, because a two-point
 * scale gives the curve two points and pushes the area toward 0.5 for reasons that are about the
 * instrument rather than the person. Every published band is measured on subjects whose scales
 * carried 4-12 distinct levels, which is where this product's seven-level scale sits.
 */

/** Bump when the corpus or the estimator changes. Readings across versions are not comparable. */
export const SENSITIVITY_REFERENCE_VERSION = 1;

/**
 * How strongly AUROC2 tracks being good at the first-order task, in this corpus.
 *
 * Published because it is the reason the bands are stratified at all, and because a future
 * corpus that does not reproduce it would mean the stratification is costing resolution for
 * nothing.
 */
export const ACCURACY_COUPLING = 0.5859;

export interface SensitivityBand {
  /** How many individual people the band was measured on. */
  n: number;
  /** How many datasets they came from. */
  studies: number;
  mean: number;
  sd: number;
  /** Share of people whose confidence carried ANY information about their own correctness. */
  aboveChance: number;
  /** Nearest-rank, so every figure here is a value some real person actually produced. */
  percentiles: readonly { p: number; auroc2: number }[];
}

export interface SensitivityStratum {
  /** First-order accuracy this band was measured on: [from, to). */
  from: number;
  to: number;
  band: SensitivityBand;
}

/** Every readable subject on a 4-12 level scale, whatever they scored. */
export const SENSITIVITY_REFERENCE: SensitivityBand = {
  n: 3836,
  studies: 76,
  mean: 0.65560,
  sd: 0.09293,
  aboveChance: 0.96898,
  percentiles: [
    { p: 5, auroc2: 0.51224 },
    { p: 10, auroc2: 0.53711 },
    { p: 25, auroc2: 0.59057 },
    { p: 50, auroc2: 0.65077 },
    { p: 75, auroc2: 0.71795 },
    { p: 90, auroc2: 0.78042 },
    { p: 95, auroc2: 0.82080 },
  ],
};

/**
 * The same people, split by how accurate they were.
 *
 * A stratum the corpus cannot support is ABSENT, not interpolated: the floor is
 * 200 people, and \`sensitivityBand\` returns null below it so a caller renders "no
 * reference class" rather than a band computed from a handful.
 */
export const SENSITIVITY_STRATA: readonly SensitivityStratum[] = [
  { from: 0, to: 0.6, band: {
    n: 260,
    studies: 45,
    mean: 0.53521,
    sd: 0.06614,
    aboveChance: 0.76923,
    percentiles: [
      { p: 5, auroc2: 0.44785 },
      { p: 10, auroc2: 0.47174 },
      { p: 25, auroc2: 0.50127 },
      { p: 50, auroc2: 0.53066 },
      { p: 75, auroc2: 0.57122 },
      { p: 90, auroc2: 0.61733 },
      { p: 95, auroc2: 0.64484 },
    ],
  } },
  { from: 0.6, to: 0.7, band: {
    n: 744,
    studies: 63,
    mean: 0.60709,
    sd: 0.06404,
    aboveChance: 0.97043,
    percentiles: [
      { p: 5, auroc2: 0.51019 },
      { p: 10, auroc2: 0.52497 },
      { p: 25, auroc2: 0.56039 },
      { p: 50, auroc2: 0.60513 },
      { p: 75, auroc2: 0.64955 },
      { p: 90, auroc2: 0.69360 },
      { p: 95, auroc2: 0.71227 },
    ],
  } },
  { from: 0.7, to: 0.8, band: {
    n: 1966,
    studies: 70,
    mean: 0.65457,
    sd: 0.07308,
    aboveChance: 0.98678,
    percentiles: [
      { p: 5, auroc2: 0.53646 },
      { p: 10, auroc2: 0.56051 },
      { p: 25, auroc2: 0.60327 },
      { p: 50, auroc2: 0.65402 },
      { p: 75, auroc2: 0.70365 },
      { p: 90, auroc2: 0.75221 },
      { p: 95, auroc2: 0.77526 },
    ],
  } },
  { from: 0.8, to: 0.9, band: {
    n: 705,
    studies: 52,
    mean: 0.72341,
    sd: 0.08769,
    aboveChance: 0.98865,
    percentiles: [
      { p: 5, auroc2: 0.55963 },
      { p: 10, auroc2: 0.60366 },
      { p: 25, auroc2: 0.67016 },
      { p: 50, auroc2: 0.73388 },
      { p: 75, auroc2: 0.78379 },
      { p: 90, auroc2: 0.83215 },
      { p: 95, auroc2: 0.84867 },
    ],
  } },
];

/**
 * The band a reading should be shown against: people who were about as accurate as this reader.
 *
 * Null where the corpus has no stratum for that accuracy, which is a real answer -- falling back
 * to the unconditioned band would hand the reader the confound this function exists to remove,
 * and would do it silently.
 *
 * NO FINITENESS GUARD, deliberately. One was written here first and was dead code: every
 * comparison against NaN is false, and an infinity clears no half-open interval, so the search
 * already returns null for all of them. A positive control found it by deleting the guard and
 * watching nothing fail -- the same way the closing guard in `sensitivity.ts` was found.
 */
export function sensitivityBand(accuracy: number): SensitivityBand | null {
  const stratum = SENSITIVITY_STRATA.find((s) => accuracy >= s.from && accuracy < s.to);
  return stratum?.band ?? null;
}
