/**
 * THE PORT IS DIFFERENCED AGAINST THE ORIGINAL, WHICH IS WHAT MAKES TWO COPIES SAFE.
 *
 * `research/measurement/sdt.py` produced every signal-detection number in
 * `docs/measurement/FALSIFICATION_REGISTER.md`; `research/measurement/sdt.ts` is the copy the
 * negative controls run on inside `npm test`. Two implementations of one formula are a drift
 * hazard, and `docs/decisions/README.md` names the only mode under which that is allowed:
 * `PORT_AFTER_EQUIVALENCE`. This file is the equivalence.
 *
 * THE FIXTURE IS GENERATED BY THE PYTHON, not written by hand, so it cannot be quietly
 * corrected to match a broken port. Regenerate with the snippet recorded in
 * `docs/measurement/ITEM_BANK_PROTOCOL.md`.
 */
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  computeSdt,
  loglinearRates,
  normalQuantile,
  tabulate,
  wilsonInterval,
} from "../../research/measurement/sdt.js";

interface GridCase {
  hits: number;
  misses: number;
  false_alarms: number;
  correct_rejections: number;
  hit_rate: number;
  false_alarm_rate: number;
  d_prime: number;
  criterion_c: number;
  beta: number;
  a_prime: number;
  b_double_prime_d: number;
  wilson_hit_lo: number;
  wilson_hit_hi: number;
}

const grid = JSON.parse(
  readFileSync(
    fileURLToPath(new URL("../../research/measurement/equivalence/sdt_grid.json", import.meta.url)),
    "utf8",
  ),
) as { cases: GridCase[]; correction: string };

/**
 * 1e-8 ABSOLUTE, and the number is chosen rather than tuned. Acklam's inverse-normal rational
 * approximation states a relative error below 1.15e-9; scipy's `norm.ppf` is exact to double
 * precision. The gap between them is that approximation error, so the tolerance is the error
 * bound and not "whatever made it pass". A d' this program would ever act on differs from
 * another by 1e-1, seven orders of magnitude coarser.
 */
const TOLERANCE = 1e-8;

describe("the TypeScript SDT port reproduces the Python it was ported from", () => {
  it("carries the same correction the corpus numbers were computed under", () => {
    expect(grid.correction).toContain("loglinear");
  });

  it.each(grid.cases.map((c, i) => [i, c] as const))(
    "case %i: H=%o",
    (_i, c) => {
      const counts = {
        hits: c.hits,
        misses: c.misses,
        falseAlarms: c.false_alarms,
        correctRejections: c.correct_rejections,
      };
      const r = computeSdt(counts);
      expect(r.hitRate).toBeCloseTo(c.hit_rate, 12);
      expect(r.falseAlarmRate).toBeCloseTo(c.false_alarm_rate, 12);
      expect(Math.abs(r.dPrime - c.d_prime)).toBeLessThan(TOLERANCE);
      expect(Math.abs(r.criterionC - c.criterion_c)).toBeLessThan(TOLERANCE);
      expect(Math.abs(r.beta - c.beta)).toBeLessThan(1e-7);
      expect(Math.abs(r.aPrime - c.a_prime)).toBeLessThan(TOLERANCE);
      expect(Math.abs(r.bDoublePrimeD - c.b_double_prime_d)).toBeLessThan(TOLERANCE);
      const [lo, hi] = wilsonInterval(c.hits, c.hits + c.misses);
      expect(Math.abs(lo - c.wilson_hit_lo)).toBeLessThan(TOLERANCE);
      expect(Math.abs(hi - c.wilson_hit_hi)).toBeLessThan(TOLERANCE);
    },
  );
});

describe("the published worked example, so the formulae are pinned to the paper", () => {
  /*
   * Stanislaw & Todorov (1999): with H = .75 and F = .25, d' = 1.349, c = 0 and beta = 1. This is
   * the one case in this file that comes from OUTSIDE this repository, and it is the reason the
   * grid above is evidence about arithmetic rather than evidence about agreement between two
   * things that could both be wrong.
   */
  it("H=.75 F=.25 gives d'=1.349, c=0, beta=1", () => {
    const r = computeSdt(
      { hits: 750, misses: 250, falseAlarms: 250, correctRejections: 750 },
      "none",
    );
    expect(r.dPrime).toBeCloseTo(1.349, 3);
    expect(r.criterionC).toBeCloseTo(0, 10);
    expect(r.beta).toBeCloseTo(1, 10);
  });

  it("z(.5) is 0 and the quantile is antisymmetric", () => {
    expect(normalQuantile(0.5)).toBeCloseTo(0, 9);
    expect(normalQuantile(0.975)).toBeCloseTo(1.959964, 5);
    expect(normalQuantile(0.025)).toBeCloseTo(-1.959964, 5);
  });
});

describe("the refusals, which are the part that keeps a ceiling from being reported as an effect", () => {
  it("refuses an uncorrected extreme rate instead of returning infinity", () => {
    expect(() =>
      computeSdt({ hits: 30, misses: 0, falseAlarms: 0, correctRejections: 30 }, "none"),
    ).toThrow(/extreme rate/);
  });

  it("refuses a table with no trials of one type", () => {
    expect(() =>
      computeSdt({ hits: 10, misses: 5, falseAlarms: 0, correctRejections: 0 }, "none"),
    ).toThrow(/undefined, not infinite/);
  });

  it("corrects a perfect table to a finite ceiling rather than to infinity", () => {
    const r = computeSdt({ hits: 30, misses: 0, falseAlarms: 0, correctRejections: 30 });
    expect(Number.isFinite(r.dPrime)).toBe(true);
    expect(r.dPrime).toBeGreaterThan(3);
  });

  it("refuses to score an UNKNOWN item rather than shrinking a denominator", () => {
    expect(() =>
      tabulate([
        { triggerState: "positive", behaviour: 1 },
        { triggerState: "unknown", behaviour: 0 },
      ]),
    ).toThrow(/excluded by the item bank/);
  });

  it("applies the loglinear correction to every table, not only to extreme ones", () => {
    /*
     * A NON-EXTREME, ASYMMETRIC TABLE, deliberately. The symmetric case 5/5 is the one table
     * where the correction is invisible -- 5.5/11 is exactly 0.25*2 -- so asserting on it would
     * have passed against an implementation that only corrects zeros and ones. 5 hits in 20
     * signal trials is 0.25 raw and 0.2619 corrected, and nothing about that table is extreme.
     */
    const { hitRate, falseAlarmRate } = loglinearRates({
      hits: 5,
      misses: 15,
      falseAlarms: 5,
      correctRejections: 5,
    });
    expect(hitRate).toBeCloseTo(5.5 / 21, 12);
    expect(hitRate).not.toBeCloseTo(0.25, 3);
    expect(falseAlarmRate).toBeCloseTo(5.5 / 11, 12);
  });
});
